# Generated by Django 3.0.5 on 2020-08-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.CharField(choices=[('T', '15-18'), ('Y', '18-21'), ('O', '30+'), ('MA', '40-60'), ('A', '21-40')], max_length=2)),
                ('Activity', models.CharField(choices=[('M', 'MIDDLE'), ('H', 'HIGH'), ('L', 'LOW')], max_length=1)),
            ],
        ),
    ]
