# Generated by Django 3.1.1 on 2020-09-09 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.CharField(choices=[('Y', '18-21'), ('MA', '40-60'), ('A', '21-40'), ('T', '15-18'), ('O', '30+')], max_length=2)),
                ('Activity', models.CharField(choices=[('H', 'HIGH'), ('M', 'MIDDLE'), ('L', 'LOW')], max_length=1)),
                ('Email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('Additional', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.activityform')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
