# Generated by Django 3.0.5 on 2020-08-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityform',
            name='Additional',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activityform',
            name='Email',
            field=models.EmailField(db_index=True, default=0, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activityform',
            name='Activity',
            field=models.CharField(choices=[('L', 'LOW'), ('H', 'HIGH'), ('M', 'MIDDLE')], max_length=1),
        ),
        migrations.AlterField(
            model_name='activityform',
            name='Age',
            field=models.CharField(choices=[('Y', '18-21'), ('T', '15-18'), ('MA', '40-60'), ('O', '30+'), ('A', '21-40')], max_length=2),
        ),
    ]
