# Generated by Django 3.0.5 on 2020-08-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200802_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityform',
            name='Activity',
            field=models.CharField(choices=[('H', 'HIGH'), ('M', 'MIDDLE'), ('L', 'LOW')], max_length=1),
        ),
        migrations.AlterField(
            model_name='activityform',
            name='Age',
            field=models.CharField(choices=[('MA', '40-60'), ('T', '15-18'), ('A', '21-40'), ('O', '30+'), ('Y', '18-21')], max_length=2),
        ),
    ]
