# Generated by Django 3.0.5 on 2020-08-03 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200802_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityform',
            name='Activity',
            field=models.CharField(choices=[('M', 'MIDDLE'), ('L', 'LOW'), ('H', 'HIGH')], max_length=1),
        ),
        migrations.AlterField(
            model_name='activityform',
            name='Age',
            field=models.CharField(choices=[('MA', '40-60'), ('A', '21-40'), ('O', '30+'), ('Y', '18-21'), ('T', '15-18')], max_length=2),
        ),
    ]
