# Generated by Django 3.0.5 on 2020-08-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200803_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityform',
            name='Activity',
            field=models.CharField(choices=[('H', 'HIGH'), ('L', 'LOW'), ('M', 'MIDDLE')], max_length=1),
        ),
        migrations.AlterField(
            model_name='activityform',
            name='Age',
            field=models.CharField(choices=[('A', '21-40'), ('Y', '18-21'), ('T', '15-18'), ('O', '30+'), ('MA', '40-60')], max_length=2),
        ),
    ]
