# Generated by Django 3.0.5 on 2020-08-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200810_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityform',
            name='Activity',
            field=models.CharField(choices=[('L', 'LOW'), ('H', 'HIGH'), ('M', 'MIDDLE')], max_length=1),
        ),
        migrations.AlterField(
            model_name='activityform',
            name='Age',
            field=models.CharField(choices=[('T', '15-18'), ('Y', '18-21'), ('O', '30+'), ('A', '21-40'), ('MA', '40-60')], max_length=2),
        ),
    ]
